from enum import Enum


class DataClassification(str, Enum):
    PUBLIC = "PUBLIC"
    LICENSED = "LICENSED"
    USER_PROVIDED = "USER_PROVIDED"
    SIMULATED = "SIMULATED"


class AgentStatus(str, Enum):
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class AgentType(str, Enum):
    # Fundamental Research Team
    SUPPLY = "SUPPLY"
    DEMAND = "DEMAND"
    STORAGE = "STORAGE"
    WEATHER = "WEATHER"
    LNG = "LNG"
    PIPELINE = "PIPELINE"
    POWER_MARKET = "POWER_MARKET"
    # Market Intelligence Team
    MARKET_DATA = "MARKET_DATA"
    NEWS_INTELLIGENCE = "NEWS_INTELLIGENCE"
    EVENT_DETECTION = "EVENT_DETECTION"
    SENTIMENT = "SENTIMENT"
    # Quantitative Team
    FORECASTING = "FORECASTING"
    REGIME_DETECTION = "REGIME_DETECTION"
    RELATIVE_VALUE = "RELATIVE_VALUE"
    BACKTESTING = "BACKTESTING"
    # Strategy Team
    DIRECTIONAL_STRATEGY = "DIRECTIONAL_STRATEGY"
    CALENDAR_SPREAD_STRATEGY = "CALENDAR_SPREAD_STRATEGY"
    BASIS_STRATEGY = "BASIS_STRATEGY"
    STORAGE_ARBITRAGE_STRATEGY = "STORAGE_ARBITRAGE_STRATEGY"
    LNG_ARBITRAGE_STRATEGY = "LNG_ARBITRAGE_STRATEGY"
    VOLATILITY_STRATEGY = "VOLATILITY_STRATEGY"
    EVENT_STRATEGY = "EVENT_STRATEGY"
    # Investment Committee
    BULL = "BULL"
    BEAR = "BEAR"
    SKEPTIC = "SKEPTIC"
    DATA_INTEGRITY = "DATA_INTEGRITY"
    PORTFOLIO = "PORTFOLIO"
    # Independent Risk Organization
    MARKET_RISK = "MARKET_RISK"
    PORTFOLIO_RISK = "PORTFOLIO_RISK"
    LIQUIDITY_RISK = "LIQUIDITY_RISK"
    DATA_RISK = "DATA_RISK"
    MODEL_RISK = "MODEL_RISK"
    RISK_GOVERNOR = "RISK_GOVERNOR"
    # Executive
    CHIEF_TRADING_AGENT = "CHIEF_TRADING_AGENT"
    CHIEF_INVESTMENT_AGENT = "CHIEF_INVESTMENT_AGENT"


class Direction(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    SPREAD = "SPREAD"


class InstrumentType(str, Enum):
    FUTURE = "FUTURE"
    OPTION = "OPTION"
    CALENDAR_SPREAD = "CALENDAR_SPREAD"
    BASIS = "BASIS"
    PHYSICAL = "PHYSICAL"


class RecommendedAction(str, Enum):
    APPROVE_FOR_REVIEW = "APPROVE_FOR_REVIEW"
    REJECT = "REJECT"
    WAIT_FOR_MORE_DATA = "WAIT_FOR_MORE_DATA"
    REDUCE_SIZE = "REDUCE_SIZE"


class RiskVerdict(str, Enum):
    ALLOW = "ALLOW"
    BLOCK = "BLOCK"
    BLOCK_NEW_RISK = "BLOCK_NEW_RISK"
    HALT = "HALT"
    REJECT = "REJECT"
    REQUIRE_HUMAN = "REQUIRE_HUMAN"


class ApprovalState(str, Enum):
    DRAFT = "DRAFT"
    AI_REVIEW = "AI_REVIEW"
    RISK_REVIEW = "RISK_REVIEW"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    APPROVED_FOR_PAPER_TRADING = "APPROVED_FOR_PAPER_TRADING"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    EXECUTED_SIMULATION = "EXECUTED_SIMULATION"
    CLOSED = "CLOSED"


class ApprovalAction(str, Enum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    MODIFY = "MODIFY"
    CHALLENGE = "CHALLENGE"
    REQUEST_MORE_ANALYSIS = "REQUEST_MORE_ANALYSIS"
    REDUCE_POSITION = "REDUCE_POSITION"
    CHANGE_INVALIDATION_CONDITION = "CHANGE_INVALIDATION_CONDITION"


class OutcomeQuadrant(str, Enum):
    GOOD_DECISION_GOOD_OUTCOME = "GOOD_DECISION_GOOD_OUTCOME"
    GOOD_DECISION_BAD_OUTCOME = "GOOD_DECISION_BAD_OUTCOME"
    BAD_DECISION_GOOD_OUTCOME = "BAD_DECISION_GOOD_OUTCOME"
    BAD_DECISION_BAD_OUTCOME = "BAD_DECISION_BAD_OUTCOME"


class Regime(str, Enum):
    NORMAL = "NORMAL"
    LOW_VOLATILITY = "LOW_VOLATILITY"
    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    WEATHER_SHOCK = "WEATHER_SHOCK"
    SUPPLY_SHOCK = "SUPPLY_SHOCK"
    DEMAND_SHOCK = "DEMAND_SHOCK"
    STORAGE_STRESS = "STORAGE_STRESS"
    LNG_SHOCK = "LNG_SHOCK"
    PIPELINE_CONSTRAINT = "PIPELINE_CONSTRAINT"
    GEOPOLITICAL_SHOCK = "GEOPOLITICAL_SHOCK"
